### ISSUE TITLE
When getting error when downloading, the error is not shown

### ISSUE THREAD

**Issue by HeruEwasham** [jvatic/audible-downloader#38]
Hello.

I have a problem with one specific title I try to backup. I found out that it each time just "skips" it entirely (the log say just Skipping (ie. the error I see is created at line 280 at cli.go).

The problem I see is that apart from that line, the error is not shown anywhere. The output.log says nothing more than this, and no error is shown either in the cmd or any other place I can see. Is it a bug with the showing of the "real" error, or is that error maybe empty (error contains whitespaces or something like this only maybe)?

It is a pain in the butt to not knowing why it has problems with this one book while all other titles go fine.

**Comment by jvatic** [comment]
I'm guessing the title starts with `Part`? The latest release (v0.0.8) should fix this (fixed this and a few other things in December and forgot to make a release, so just did so with the latest master).

**Comment by HeruEwasham** [comment]
The books title did not start with `Part`, but the word `Parts` was the second word, so it did at least had the word `Part` in it :)

When running the new release, it downloads fine, without any issue.
